<?php
	$smartProductData = $block->getSmartProductData();
?>
<div class="entry-edit form-inline">
	<fieldset id="rule_productgird_fieldset" class="fieldset admin__fieldset ">
		<legend class="admin__legend legend">
			<span>Configure Product By Id's</span>
		</legend>
		<div class="field">
		    <label class="label">
		    	<span>Product By Id's</span>
		    </label>
		    <select id="set_sku" name="set_sku" title="Status">
				<option value="0" <?php if(isset($smartProductData['set_sku']) && $smartProductData['set_sku'] == 1){ echo ""; }else{ echo  "selected='selected'"; } ?> >No</option>
				<option value="1" <?php if(isset($smartProductData['set_sku']) && $smartProductData['set_sku'] == 1){ echo  "selected='selected'"; } ?> >Yes</option>
			</select>
		</div>
		<div id="sku_chooser" style="<?php if(isset($smartProductData['set_sku']) && $smartProductData['set_sku'] == 1){ echo 'display:block;'; }else{ echo 'display:none;'; } ?>">
			<span class="rule-param" id="rule-param" style="float:left;">
			    SKU&nbsp;<a href="javascript:void(0)" class="label">is</a>&nbsp;&nbsp;
			</span>
			<span class="rule-param rule-param-edit" style="margin-top:8px;">
			    <a href="javascript:void(0)" id="labelData" style="display: block;text-overflow: ellipsis;white-space: nowrap;width:250px;display: inline-block;overflow:hidden;"><?php if(isset($smartProductData['set_sku']) && $smartProductData['set_sku'] == 1){ echo  $smartProductData['sku_data']; }else { echo ". . . ."; } ?></a>
			    <span class="element" id="element">
			        <input type="text" id="sku_data" name="sku_data" value="<?php if(isset($smartProductData['set_sku']) && $smartProductData['set_sku'] == 1){ echo  $smartProductData['sku_data']; } ?>"/>
			        <label>
			            <a href="javascript:void(0)" class="rule-chooser-trigger" id="rule-chooser-trigger">
			                <img src="<?php echo $this->getViewFileUrl('Emipro_Smartproductselector::images/rule_chooser_trigger.gif'); ?>" alt="" class="v-middle rule-chooser-trigger" title="Open Chooser">
			            </a>
			        </label>
			        <a href="javascript:void(0)" class="rule-param-apply" id="rule-param-apply">
			            <img src="<?php echo $this->getViewFileUrl('Emipro_Smartproductselector::images/rule_component_apply.gif'); ?>" class="v-middle" alt="Apply" title="Apply">
			        </a>
			    </span>
			</span>
		<div data-rale="pannel" >
			<div id="grid" style="border: 1px solid #ccc;margin: 20px;overflow: auto;padding: 15px 10px; display:none;"></div>
     	</div>
		</div>
	</fieldset>
</div>
<script type="text/javascript">
require(['jquery'], function ($) {
	jQuery('document').ready(function () {
		var skuCss = "<?php if(isset($smartProductData['set_sku']) && $smartProductData['set_sku'] == 1){ echo  '1'; }else{ echo '0'; } ?>";
		if(skuCss == '1'){
			document.getElementById('rule_newactiontable_fieldset').style.display='none';
			document.getElementById('rule_newaction_fieldset').style.display = 'none';
		}
		var temp = 0;
		jQuery("#set_sku").change(function () {
			if($("#set_sku").val() == 1)
			{
				document.getElementById('sku_chooser').style.display = 'block';
				document.getElementById('rule_newactiontable_fieldset').style.display='none';
				document.getElementById('rule_newaction_fieldset').style.display = 'none';
			}
			else
			{
				document.getElementById('sku_chooser').style.display = 'none';
				document.getElementById('grid').style.display = 'none';
				document.getElementById('rule_newactiontable_fieldset').style.display='block';
				document.getElementById('rule_newaction_fieldset').style.display = 'block';
			}
		});

		jQuery("#rule-chooser-trigger").click(function () {
			var key = "<?php echo $block->getPostformKey() ?>";
			var ruleId = "<?php echo $block->getPostId() ?>";
			document.getElementById('grid').style.display = 'block';
			if(temp == 0)
			{
				request = $.ajax({

		                    url: "<?php echo $block->getPostformUrl() ?>",
		                    type: "post",
		                    data: {"rule_id":ruleId,"key": key}
		                });
				temp = 1;
	        	request.done(function (response, textStatus, jqXHR) {
	                $("#grid").prepend(response);

	            });
	        }
		});
		document.getElementById('element').style.display = 'none';
		jQuery("#rule-param-apply").click(function () {
			document.getElementById('grid').style.display = 'none';
			var textValue = document.getElementById('sku_data').value;
			document.getElementById('element').style.display = 'none';
			if(textValue != ''){
				document.getElementById('labelData').innerHTML = textValue;
			}
			else{
				document.getElementById('labelData').innerHTML = '. . . .';
			}
			document.getElementById('labelData').style.display = 'block';
			document.getElementById('rule-param').style.marginTop = "0px";
		});

		jQuery("#labelData").click(function () {
			document.getElementById('rule-param').style.marginTop = "8px";
			document.getElementById('labelData').style.display = 'none';
			document.getElementById('element').style.display = 'block';
		});
	});
});
</script>
