<script type="text/javascript">
require(['jquery'], function ($) {
	jQuery('document').ready(function () {
		jQuery('.checkbox').change(function(){
			var arr = [];
			var values = $.map($("input[type=checkbox]:checked"), function(el) {
		        if(el.value != 'on')
		        {
		        	arr.push($.trim($(el).closest("tr").find('.col-sku').text()));
		        }
		    });
		    jQuery("#sku_data").val(arr);
		});
	});
});
</script>