<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	function getAttribute($productAttribute=Null)
	{
		$option=NULL;
		$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
		$attributes = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\Attribute\Collection')->addVisibleFilter();
		$prodAttr = [];
		foreach($attributes as $attribute)
		{
			$prodAttr[] = [
				'label' => $attribute->getData('frontend_label'),
				'value' => $attribute->getData('attribute_code')
			];
		}
		foreach($prodAttr as $value)
		{
			$val=$value["value"];
			if($val==$productAttribute)
			{
				$option.="<option selected='selected' value=".$val.">".$value["label"]."</option>";
			}
			else
			{
				$option.="<option value=".$val.">".$value["label"]."</option>";
			}
		}
	return $option;
	}

	function getCondition($condition=Null)
	{
		$option=null;
		$optionArray = array(
		array("label" => "Equals","value" => "eq"),
        array("label" => "Not equal to","value" => "neq"),
        array("label" => "Having","value" => "like"),
        array("label" => "Not Having","value" => "nlike"),
        array("label" => "Greater than","value" => "gt"),
        array("label" => "Greater than or equal to","value" => "gteq"),
        array("label" => "less than","value" => "lt"),
        array("label" => "less then or equal to","value" => "lteq"),
        );
		foreach($optionArray as $value)
		{
			$val=$value["value"];
			if($val==$condition)
			{
				$option.="<option selected='selected' value=".$val.">".$value["label"]."</option>";
			}
			else
			{
				$option.="<option value=".$val.">".$value["label"]."</option>";
			}
		}
	return $option;
	}
?>

<input type="hidden" name="delgetAttribute" id="delgetAttribute" >

<div class="entry-edit form-inline">
	<fieldset id="rule_newactiontable_fieldset" class="fieldset admin__fieldset ">
		<legend class="admin__legend legend">
			<span>
					Configure product attributes condition for display alternative products
			</span>
		</legend>

		<table id="table" class="data-table">
			<thead>
			    <tr>
			        <th class="col-prod-attr required">
			        	Alternate product’s
			        	<span class="required">*</span>
			        </th>
			        <th class="col-is"></th>
			        <th class="col-cond">current product’s value</th>
			        <th class="col-actions">&nbsp;</th>
			    </tr>
			</thead>
			<tbody class="ui-sortable">
				<?php
				$id=$this->getRequest()->getParam("rule_id");
				if(!empty($id))
				{
					$productAttribute = '';
					$condition = '';
					$getAttribute = $objectManager->create('Emipro\Smartproductselector\Model\Rule')->load($id);
					$conditions = unserialize($getAttribute->getAttributeConditions());
					$i=0;
					if($conditions)
					{
						foreach($conditions as $value)
						{
							$productAttribute= $value["product_attr"];
							$condition= $value["condition"];

					?>
				    <tr>
				      	<td class="col-prod-attr select-opt-prod-attr">
					        <select name="attribute_conditions[<?php echo $i;?>][product_attr]"><?php echo getAttribute($productAttribute); ?>
								</select>
				      	</td>
				      	<td class="col-is select-opt-is">&nbsp; &nbsp; &nbsp;is</td>
				      	<td class="col-cond select-opt-cond">
					        <select name="attribute_conditions[<?php echo $i;?>][condition]"><?php echo getCondition($condition); ?>
							</select>
				      	</td>
				      	<td class="col-actions col-delete ">
				            <button title="Delete Row" type="button" class="action- scalable delete delete-select-row" value="Delete" onClick="del(<?php echo $id; ?>,this)">
				            <span>Delete Row</span>
				        </button>
				      </td>
				    </tr>
			    <?php
						$i++;
						}
					}
				}
				?>
			</tbody>
			<tfoot>
		        <tr>
		            <td colspan="4">
		                <button title="Add New Row" type="button" class="add add-select-row"  onclick="addRow()">
		                    <span>Add New Row</span>
		                </button>
		            </td>
		        </tr>
		    </tfoot>
		</table>

		<span>
			<b> Note : </b>Choose relationship you want to establish with selected products
		</span>
	</fieldset>
</div>

<script>
	var delrow="";
	function del(val1,obj)
	{
		alert("Are You Sure To Delete This Data?");
		if(delrow==""){
			delrow+=val1;
		}
		else{
			delrow+=","+val1;
		}
		document.getElementById("delgetAttribute").value=delrow;

		jQuery(obj).closest('tr').remove();
		rowCount=jQuery('#table tr').length-1;
		if(rowCount!=0){
		jQuery("#chckval").val(rowCount);
		}
		else{
		jQuery("#chckval").removeAttr("value");
		}
	}

	function chng(val)
	{
		var value = val.options[val.selectedIndex].value;
		if(value=='txt'){
			document.getElementById('seperator').disabled=false;
		}
		else{
			document.getElementById('seperator').disabled=true;
		}
	}

	var rowCount =0;
	function addRow()
	{
		rowCount=jQuery('#table tr').length;
		jQuery("#chckval").val(rowCount);
		jQuery('#table').append('<tr>'+"<td class=col-prod-attr select-opt-prod-attr><select name=attribute_conditions["+rowCount+"][product_attr]><?php echo getAttribute(); ?></select></td><td class=col-is select-opt-is>&nbsp; &nbsp; &nbsp;is</td>"+"<td class=col-cond select-opt-cond><select name=attribute_conditions["+rowCount+"][condition]><?php echo getCondition(); ?></select></td>"+'<td class=col-actions col-delete><button title="Delete Row" class="action- scalable delete delete-select-row" value="Delete" type="button" onclick="deleteRow(this)">'+'<span>Remove</span>'+'</button>'+'</tr>');
	}

	function deleteRow(obj)
	{
		jQuery(obj).closest('tr').remove();
		rowCount=jQuery('#table tr').length-1;
		if(rowCount!=0){
			jQuery("#chckval").val(rowCount);
		}
		else{
			jQuery("#chckval").removeAttr("value");
		}
	}
</script>
